import Foundation
import SwiftUI

enum Language: String {
    case english = "en"
    case vietnamese = "vi"
}

class Localization: ObservableObject {
    static let shared = Localization()
    
    @Published var currentLanguage: Language {
        didSet {
            UserDefaults.standard.set(currentLanguage.rawValue, forKey: "currentLanguage")
            NotificationCenter.default.post(name: .languageChanged, object: nil)
        }
    }
    
    private var translations: [String: [Language: String]] = [
        "settings": [.english: "Settings", .vietnamese: "Cài đặt"],
        "access_permissions": [.english: "Access Permissions", .vietnamese: "Quyền truy cập"],
        "accessibility_status": [.english: "Accessibility Status", .vietnamese: "Trạng thái quyền truy cập"],
        "allow_access": [.english: "Allow Access", .vietnamese: "Cho phép truy cập"],
        "history_settings": [.english: "History Settings", .vietnamese: "Cài đặt lịch sử"],
        "max_history_items": [.english: "Maximum History Items", .vietnamese: "Số lượng mục tối đa"],
        "shortcut_settings": [.english: "Shortcut Settings", .vietnamese: "Cài đặt phím tắt"],
        "current_shortcut": [.english: "Current Shortcut", .vietnamese: "Phím tắt hiện tại"],
        "recording": [.english: "Recording...", .vietnamese: "Đang ghi..."],
        "change": [.english: "Change", .vietnamese: "Thay đổi"],
        "choose": [.english: "Choose", .vietnamese: "Chọn"],
        "language_settings": [.english: "Language Settings", .vietnamese: "Cài đặt ngôn ngữ"],
        "select_language": [.english: "Select Language", .vietnamese: "Chọn ngôn ngữ"],
        "shortcut": [.english: "Shortcut", .vietnamese: "Phím tắt"],
        "open_clipboard_history": [.english: "Open clipboard history:", .vietnamese: "Mở lịch sử clipboard:"],
        "language": [.english: "Language", .vietnamese: "Ngôn ngữ"],
        "appearance": [.english: "Appearance", .vietnamese: "Giao diện"],
        "theme": [.english: "Theme:", .vietnamese: "Chủ đề:"],
        "theme_system": [.english: "System", .vietnamese: "Hệ thống"],
        "theme_light": [.english: "Light", .vietnamese: "Sáng"],
        "theme_dark": [.english: "Dark", .vietnamese: "Tối"],
        "theme_custom": [.english: "Custom", .vietnamese: "Tùy chỉnh"],
        "history": [.english: "History", .vietnamese: "Lịch sử"],
        "save_and_close": [.english: "Save & Close", .vietnamese: "Lưu & Đóng"],
        "buy_coffee": [.english: "Buy me a coffee", .vietnamese: "Mua cho tôi một ly cà phê"],
        "contact": [.english: "Contact & Feedback", .vietnamese: "Liên hệ & góp ý"],
        "quit": [.english: "Quit", .vietnamese: "Thoát"],
        "check_for_updates": [.english: "Check for Updates", .vietnamese: "Kiểm tra cập nhật"],
        "update_available": [.english: "Update Available", .vietnamese: "Có bản cập nhật mới"],
        "update_new_version": [.english: "Version %@ is available (current: %@)", .vietnamese: "Phiên bản %@ đã có (hiện tại: %@)"],
        "update_download": [.english: "Download & Install", .vietnamese: "Tải & Cài đặt"],
        "update_later": [.english: "Later", .vietnamese: "Để sau"],
        "update_no_update": [.english: "No Update Available", .vietnamese: "Không có bản cập nhật"],
        "update_current_version": [.english: "You are using the latest version (%@)", .vietnamese: "Bạn đang dùng phiên bản mới nhất (%@)"],
        "update_ready": [.english: "Update Ready", .vietnamese: "Sẵn sàng cập nhật"],
        "update_restart_message": [.english: "The app needs to restart to complete the update. Your permissions will be preserved.", .vietnamese: "Ứng dụng cần khởi động lại để hoàn tất cập nhật. Quyền truy cập sẽ được giữ nguyên."],
        "update_restart_now": [.english: "Restart Now", .vietnamese: "Khởi động lại ngay"],
        "update_checking": [.english: "Checking for updates...", .vietnamese: "Đang kiểm tra cập nhật..."],
        "update_downloading": [.english: "Downloading update...", .vietnamese: "Đang tải bản cập nhật..."],
        "update_version": [.english: "Version", .vietnamese: "Phiên bản"],
        "update_auto_check": [.english: "Check for updates on launch", .vietnamese: "Tự động kiểm tra khi khởi động"],
        "update_cannot_install": [.english: "Cannot Install Update", .vietnamese: "Không thể cài đặt cập nhật"],
        "update_move_to_applications": [.english: "Please drag CursorKit.app into your Applications folder before updating. The app cannot update itself when running from a read-only volume (such as a mounted DMG).", .vietnamese: "Vui lòng kéo CursorKit.app vào thư mục Applications trước khi cập nhật. App không thể tự cập nhật khi chạy từ ổ đĩa chỉ đọc (như DMG đã mount)."],
        "update_download_corrupted": [.english: "Update download was incomplete. Please try again.", .vietnamese: "Tải cập nhật chưa hoàn tất. Vui lòng thử lại."],
        "contact_author_info": [.english: "Author information:", .vietnamese: "Thông tin tác giả:"],
        "empty_history": [.english: "Clipboard history is empty", .vietnamese: "Lịch sử clipboard trống"],
        "empty_search_no_results": [.english: "No matches found", .vietnamese: "Không tìm thấy kết quả"],
        // Filters
        "filter_all": [.english: "All", .vietnamese: "Tất cả"],
        "filter_text": [.english: "Text", .vietnamese: "Văn bản"],
        "filter_image": [.english: "Images", .vietnamese: "Hình ảnh"],
        "filter_file": [.english: "Files", .vietnamese: "Tệp tin"],
        "filter_bookmark": [.english: "Bookmarks", .vietnamese: "Bookmark"],
        "filter_otp": [.english: "OTP", .vietnamese: "OTP"],
        // Search & actions
        "search_placeholder": [.english: "Search...", .vietnamese: "Tìm kiếm..."],
        "search_tooltip": [.english: "Search", .vietnamese: "Tìm kiếm"],
        "delete_filter_tooltip": [.english: "Clear %@", .vietnamese: "Xóa %@"],
        // Item actions
        "action_copy": [.english: "Copy", .vietnamese: "Sao chép"],
        "action_save_image": [.english: "Save image", .vietnamese: "Lưu ảnh"],
        "action_open": [.english: "Open", .vietnamese: "Mở"],
        "action_open_url_browser": [.english: "Open URL in browser", .vietnamese: "Mở URL trong trình duyệt"],
        "action_open_in_browser": [.english: "Open in browser", .vietnamese: "Mở trong trình duyệt"],
        "action_show_json": [.english: "Show JSON", .vietnamese: "Hiển thị JSON"],
        "action_show_table": [.english: "Show as table", .vietnamese: "Hiển thị dạng bảng"],
        "action_export_excel_open": [.english: "Export Excel & Open", .vietnamese: "Xuất Excel & Mở"],
        "action_show_timestamp": [.english: "Show timestamp", .vietnamese: "Hiển thị timestamp"],
        "action_show_datetime": [.english: "Show date/time", .vietnamese: "Hiển thị ngày giờ"],
        "action_paste_as_image": [.english: "Paste as image", .vietnamese: "Dán như ảnh"],
        "action_pin": [.english: "Pin", .vietnamese: "Ghim"],
        "action_unpin": [.english: "Unpin", .vietnamese: "Bỏ ghim"],
        "action_bookmark": [.english: "Bookmark", .vietnamese: "Bookmark"],
        "action_unbookmark": [.english: "Remove bookmark", .vietnamese: "Bỏ bookmark"],
        "action_copy_path": [.english: "Copy path", .vietnamese: "Copy đường dẫn"],
        "action_delete": [.english: "Delete", .vietnamese: "Xóa"],
        "max_history_hint": [.english: "Valid range: 1–500", .vietnamese: "Giá trị hợp lệ: 1–500"],
        // Accessibility permission view
        "perm_window_title": [.english: "CursorKit - Permission Required", .vietnamese: "CursorKit - Yêu cầu quyền"],
        "perm_request_title": [.english: "Accessibility Permission Required", .vietnamese: "Yêu cầu quyền Accessibility"],
        "perm_request_subtitle": [.english: "For CursorKit to work optimally", .vietnamese: "Để CursorKit hoạt động tốt nhất"],
        "perm_feature_paste_title": [.english: "Auto-paste", .vietnamese: "Tự động paste"],
        "perm_feature_paste_desc": [.english: "Paste content immediately when selected from history", .vietnamese: "Paste nội dung ngay khi chọn từ lịch sử"],
        "perm_feature_cursor_title": [.english: "Cursor detection", .vietnamese: "Phát hiện con trỏ"],
        "perm_feature_cursor_desc": [.english: "Show window at the right place where you're working", .vietnamese: "Hiển thị cửa sổ đúng vị trí đang làm việc"],
        "perm_feature_keyboard_title": [.english: "Smart shortcuts", .vietnamese: "Phím tắt thông minh"],
        "perm_feature_keyboard_desc": [.english: "Simulate ⌘V for automatic paste", .vietnamese: "Giả lập Command+V để paste tự động"],
        "perm_quick_guide": [.english: "Quick guide:", .vietnamese: "Hướng dẫn nhanh:"],
        "perm_step_1": [.english: "Click 'Open System Settings'", .vietnamese: "Click nút 'Mở System Settings'"],
        "perm_step_2": [.english: "Find 'CursorKit' and toggle on", .vietnamese: "Tìm 'CursorKit' và bật toggle"],
        "perm_step_3": [.english: "Return to the app — this window will close automatically", .vietnamese: "Quay lại app - cửa sổ sẽ tự đóng"],
        "perm_stale_hint": [.english: "After update, you may need to remove CursorKit from the list and re-add it from /Applications/CursorKit.app", .vietnamese: "Sau khi update, có thể cần xoá CursorKit khỏi list rồi add lại từ /Applications/CursorKit.app"],
        "perm_open_settings": [.english: "Open System Settings", .vietnamese: "Mở System Settings"],
        "perm_quit_app": [.english: "Quit application", .vietnamese: "Thoát ứng dụng"],
        "perm_auto_close": [.english: "This window will close automatically once you grant permission", .vietnamese: "Cửa sổ này sẽ tự động đóng khi bạn cấp quyền"],
        "perm_granted_title": [.english: "Success! ✅", .vietnamese: "Thành công! ✅"],
        "perm_granted_message": [.english: "CursorKit now has Accessibility permission. You can start using the app.", .vietnamese: "CursorKit đã có quyền Accessibility. Bạn có thể bắt đầu sử dụng app."],
        "update_cancel": [.english: "Cancel download", .vietnamese: "Hủy tải"],
        "feature_privacy_disclaimer": [.english: "CursorKit history is stored unencrypted in UserDefaults. Avoid using this app for passwords or sensitive secrets.", .vietnamese: "Lịch sử CursorKit lưu plaintext trong UserDefaults. Không nên dùng app này cho mật khẩu hoặc dữ liệu nhạy cảm."],
        "use_native_ui": [.english: "Native macOS UI", .vietnamese: "Giao diện native macOS"],
        "use_native_ui_hint": [.english: "Compact list style without custom cards", .vietnamese: "Danh sách gọn theo style hệ thống, không dùng card tuỳ chỉnh"],
        "visual_effects": [.english: "Visual effects", .vietnamese: "Hiệu ứng giao diện"],
        "visual_effects_hint": [.english: "Hover shine, scale and soft shadows in the popup", .vietnamese: "Hiệu ứng gương, phóng nhẹ và bóng khi hover trong popup"],
        "popup_position": [.english: "Popup position", .vietnamese: "Vị trí hộp thoại"],
        "popup_position_hint": [.english: "Where the history popup appears relative to the cursor", .vietnamese: "Hộp thoại lịch sử sẽ xuất hiện ở đâu so với con trỏ chuột"],
        "show_item_info_line": [.english: "Show item info line", .vietnamese: "Hiện dòng thông tin của item"],
        "show_item_info_line_hint": [.english: "Index, badges, source app and time below each item", .vietnamese: "Số thứ tự, badge, app nguồn và thời gian dưới mỗi item"],
        "color_theme": [.english: "Color theme", .vietnamese: "Bộ màu"],
        "color_theme_hint": [.english: "Accent color used across the app", .vietnamese: "Màu accent dùng xuyên suốt app"],
        // Tabs
        "tab_general": [.english: "General", .vietnamese: "Chung"],
        "tab_features": [.english: "Features", .vietnamese: "Tính năng"],
        "tab_appearance": [.english: "Appearance", .vietnamese: "Giao diện"],
        "tab_info": [.english: "Info", .vietnamese: "Thông tin"],
        "info_author": [.english: "Author", .vietnamese: "Tác giả"],
        "info_links": [.english: "Links", .vietnamese: "Liên kết"],
        "info_support": [.english: "Support", .vietnamese: "Ủng hộ"],
        "info_github": [.english: "GitHub repository", .vietnamese: "Mã nguồn GitHub"],
        "info_buy_coffee_text": [.english: "If this app helps you, consider buying me a coffee ☕", .vietnamese: "Nếu app này hữu ích, mời tôi một ly cà phê ☕"],
        "launch_at_login": [.english: "Launch at login", .vietnamese: "Tự khởi động cùng máy"],
        "launch_at_login_hint": [.english: "Auto-start CursorKit when you log in to macOS", .vietnamese: "Tự động chạy CursorKit khi đăng nhập macOS"],
        "font_design": [.english: "Font", .vietnamese: "Phông chữ"],
        "font_size": [.english: "Font size", .vietnamese: "Cỡ chữ"],
        "font_design_system": [.english: "System", .vietnamese: "Hệ thống"],
        "font_design_monospaced": [.english: "Monospaced", .vietnamese: "Monospaced"],
        "font_design_rounded": [.english: "Rounded", .vietnamese: "Bo tròn"],
        "font_design_serif": [.english: "Serif", .vietnamese: "Serif"],
        // Feature toggles
        "feature_move_to_top": [.english: "Move item to top after paste", .vietnamese: "Đưa mục lên đầu sau khi dán"],
        "feature_json_to_table": [.english: "Convert JSON to table view", .vietnamese: "Chuyển JSON sang dạng bảng"],
        "feature_json_to_excel": [.english: "Convert JSON to Excel (.xlsx)", .vietnamese: "Chuyển JSON sang Excel"],
        "feature_table_to_json": [.english: "Convert table to JSON", .vietnamese: "Chuyển dạng bảng sang JSON"],
        "feature_open_url": [.english: "Open URL in browser", .vietnamese: "Mở URL trong trình duyệt"],
        "feature_timestamp": [.english: "Convert timestamp ↔ datetime", .vietnamese: "Chuyển đổi timestamp"],
        "feature_search": [.english: "Search by keyword", .vietnamese: "Tìm kiếm theo từ khóa"],
        "feature_drag_drop": [.english: "Drag-and-drop file", .vietnamese: "Kéo thả file"],
        "feature_number_shortcuts": [.english: "Cmd+1..9 to paste item by number", .vietnamese: "Cmd+1..9 để paste item theo số"],
        "feature_hide_popup_after_drag": [.english: "Hide popup after drag", .vietnamese: "Ẩn popup sau khi kéo thả"],
        "hint_navigate": [.english: "Navigate", .vietnamese: "Chọn"],
        "hint_paste": [.english: "Paste", .vietnamese: "Dán"],
        "hint_quick_paste": [.english: "Quick paste", .vietnamese: "Dán nhanh"],
        "menu_more": [.english: "More", .vietnamese: "Thêm"],
        "menu_clear_data": [.english: "Clear data", .vietnamese: "Xóa dữ liệu"],
        "clear_dialog_title": [.english: "Clear clipboard history", .vietnamese: "Xóa lịch sử clipboard"],
        "clear_dialog_message": [.english: "This action cannot be undone.", .vietnamese: "Hành động này không thể hoàn tác."],
        "clear_dialog_include_pinned": [.english: "Also clear pinned items", .vietnamese: "Xóa cả các mục đã ghim"],
        "clear_dialog_include_bookmarked": [.english: "Also clear bookmarked items", .vietnamese: "Xóa cả các mục bookmark"],
        "clear_dialog_confirm": [.english: "Clear", .vietnamese: "Xóa"],
        // OTP
        "otp_tab": [.english: "OTP", .vietnamese: "OTP"],
        "clipboard_tab": [.english: "Clipboard", .vietnamese: "Clipboard"],
        "otp_feature_enable": [.english: "OTP manager (2FA codes)", .vietnamese: "Quản lý OTP (mã 2FA)"],
        "otp_grace_period": [.english: "OTP unlock duration", .vietnamese: "Thời gian giữ mở khóa OTP"],
        "otp_grace_1": [.english: "1 minute", .vietnamese: "1 phút"],
        "otp_grace_5": [.english: "5 minutes", .vietnamese: "5 phút"],
        "otp_grace_15": [.english: "15 minutes", .vietnamese: "15 phút"],
        "otp_auto_backup_enable": [.english: "Automatic OTP backup", .vietnamese: "Tự động backup OTP"],
        "otp_auto_backup_path": [.english: "Automatic OTP backup path", .vietnamese: "Đường dẫn backup OTP tự động"],
        "otp_auto_backup_interval": [.english: "Automatic OTP backup frequency", .vietnamese: "Tần suất backup OTP tự động"],
        "otp_auto_lock_time": [.english: "Auto-lock after", .vietnamese: "Thời gian auto khóa lại"],
        "otp_backup_password_default": [.english: "Default encryption password", .vietnamese: "Mật khẩu mã hóa mặc định"],
        "otp_backup_custom_password_placeholder": [.english: "Enter custom password", .vietnamese: "Nhập mật khẩu tùy chỉnh"],
        "otp_backup_custom_password_set": [.english: "Custom password is saved.", .vietnamese: "Đã lưu mật khẩu tùy chỉnh."],
        "otp_backup_custom_password_not_set": [.english: "No custom password saved yet.", .vietnamese: "Chưa lưu mật khẩu tùy chỉnh."],
        "otp_auto_backup_hint": [.english: "Automatic backup runs when the app is open and uses the saved custom password, so it can run unattended.", .vietnamese: "Backup tự động chạy khi app đang mở và dùng mật khẩu tùy chỉnh đã lưu, nên có thể chạy hoàn toàn tự động."],
        "otp_hours_value": [.english: "%d hour(s)", .vietnamese: "%d giờ"],
        "otp_minutes_value": [.english: "%d minute(s)", .vietnamese: "%d phút"],
        "otp_unlock_title": [.english: "OTP is locked", .vietnamese: "OTP đang khóa"],
        "otp_unlock_touchid": [.english: "Unlock with Touch ID", .vietnamese: "Mở khóa bằng Touch ID"],
        "otp_unlock_reason": [.english: "Unlock your OTP codes", .vietnamese: "Mở khóa danh sách mã OTP"],
        "otp_enter_pin": [.english: "Enter 6-digit PIN", .vietnamese: "Nhập mã PIN 6 số"],
        "otp_setup_pin_title": [.english: "Set a 6-digit PIN", .vietnamese: "Đặt mã PIN 6 số"],
        "otp_setup_pin_confirm": [.english: "Confirm PIN", .vietnamese: "Xác nhận PIN"],
        "otp_pin_mismatch": [.english: "PINs do not match", .vietnamese: "PIN không khớp"],
        "otp_pin_wrong": [.english: "Wrong PIN", .vietnamese: "Sai PIN"],
        "otp_locked_out": [.english: "Too many attempts. Try again in %ds", .vietnamese: "Sai quá nhiều lần. Thử lại sau %d giây"],
        "otp_search_placeholder": [.english: "Search OTP...", .vietnamese: "Tìm OTP..."],
        "otp_empty": [.english: "No OTP yet. Use 'Manage OTP' to add.", .vietnamese: "Chưa có OTP. Dùng 'Quản lý OTP' để thêm."],
        "otp_copied": [.english: "Code copied", .vietnamese: "Đã copy mã"],
        "otp_manage": [.english: "Manage OTP", .vietnamese: "Quản lý OTP"],
        "otp_add": [.english: "Add OTP", .vietnamese: "Thêm OTP"],
        "otp_name": [.english: "Name", .vietnamese: "Tên"],
        "otp_issuer": [.english: "Issuer (optional)", .vietnamese: "Nhà cung cấp (tùy chọn)"],
        "otp_secret": [.english: "Secret key (base32)", .vietnamese: "Khóa bí mật (base32)"],
        "otp_advanced": [.english: "Advanced", .vietnamese: "Nâng cao"],
        "otp_algorithm": [.english: "Algorithm", .vietnamese: "Thuật toán"],
        "otp_digits": [.english: "Digits", .vietnamese: "Số chữ số"],
        "otp_period": [.english: "Period (s)", .vietnamese: "Chu kỳ (giây)"],
        "otp_add_manual": [.english: "Manual entry", .vietnamese: "Nhập tay"],
        "otp_add_qr_image": [.english: "From QR image", .vietnamese: "Từ ảnh QR"],
        "otp_add_clipboard": [.english: "From clipboard image", .vietnamese: "Từ ảnh trong clipboard"],
        "otp_save": [.english: "Save", .vietnamese: "Lưu"],
        "otp_cancel": [.english: "Cancel", .vietnamese: "Hủy"],
        "otp_delete": [.english: "Delete", .vietnamese: "Xóa"],
        "otp_edit": [.english: "Edit", .vietnamese: "Sửa"],
        "otp_invalid_secret": [.english: "Invalid base32 secret", .vietnamese: "Khóa base32 không hợp lệ"],
        "otp_qr_not_found": [.english: "No valid QR code found", .vietnamese: "Không tìm thấy mã QR hợp lệ"],
        "otp_need_screen_permission": [.english: "Grant Screen Recording permission in System Settings, then try again", .vietnamese: "Hãy cấp quyền Quay màn hình trong System Settings rồi thử lại"],
        "otp_export": [.english: "Export OTP backup", .vietnamese: "Xuất backup OTP"],
        "otp_import": [.english: "Import OTP backup", .vietnamese: "Nhập backup OTP"],
        "otp_export_warning": [.english: "The file is encrypted with your backup password. Keep it safe; losing the password means losing the data.", .vietnamese: "File được mã hóa bằng mật khẩu backup. Hãy giữ cẩn thận; mất mật khẩu là mất dữ liệu."],
        "otp_import_done": [.english: "Imported %d new item(s)", .vietnamese: "Đã nhập %d mục mới"],
        "otp_import_failed": [.english: "Import failed: wrong backup password or corrupt file", .vietnamese: "Nhập thất bại: sai mật khẩu backup hoặc file hỏng"],
        "otp_added": [.english: "Added %@", .vietnamese: "Đã thêm %@"],
        "otp_export_failed": [.english: "Export failed", .vietnamese: "Xuất thất bại"],
        "otp_secret_duplicate": [.english: "This secret already exists", .vietnamese: "Khóa bí mật này đã tồn tại"],
        "clear_dialog_cancel": [.english: "Cancel", .vietnamese: "Hủy"]
    ]
    
    init() {
        if let savedLanguage = UserDefaults.standard.string(forKey: "currentLanguage"),
           let language = Language(rawValue: savedLanguage) {
            self.currentLanguage = language
        } else {
            self.currentLanguage = .english
        }
    }
    
    func localizedString(_ key: String) -> String {
        return translations[key]?[currentLanguage] ?? key
    }
}

extension Notification.Name {
    static let languageChanged = Notification.Name("languageChanged")
} 
